### ISSUE TITLE
Invalid YAML Files Cause smbcrawler to Crash

### ISSUE THREAD

**Issue by FLX-0x00** [SySS-Research/smbcrawler#5]
#### Description
Currently, `smbcrawler` automatically loads all YAML files in the current directory as profiles. If any of these YAML files are invalid or do not conform to the expected structure, the program crashes with an error:

```
C 2025-03-19 12:44:53 Error while collecting profiles: 'list' object has no attribute 'keys'
```

#### Steps to Reproduce
1. Create an invalid YAML file in the current directory, e.g., `test.yaml`:
   ```yaml
   - false
   - go
   - - true
     - false
     - wear: true
       anything: -1629067790.7358913
       structure: success
       business: 757915021
       aboard: false
       congress: false
     - false
     - occur
     - keep
   - false
   - state
   - 293477217.97167253
   ```
2. Run `smbcrawler`:
   ```sh
   smbcrawler --debug --verbose crawl -u test -p test
   ```
3. The program crashes with:
   ```
   Error while collecting profiles: 'list' object has no attribute 'keys'
   ```

#### Expected Behavior
- `smbcrawler` should **not** attempt to load every YAML file in the current directory as a profile by default.
- Instead, only explicitly specified YAML files (via a command-line parameter) should be loaded as profiles.
- If invalid YAML files are encountered, the program should log a warning instead of crashing.

#### Environment
- `smbcrawler` version: 1.1.0
- OS: Arch Linux
